project:
  type: book
  output-dir: docs

book:
  title: "Estruturação e Análise de Dados Jurídicos"
  subtitle: "Fundamentos de Jurimetria e IA"
  navbar:
    background: "#283747"
    search: true
    left:
      - text: "Home"
        file: index.qmd
      #- intro.qmd
      #- summary.qmd
      #- pesquisa.qmd
      #- interpretando.qmd
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub
  sidebar:
    background: "#F4F6F6"
    search: true
  image: logo_fdrp.png
  page-navigation: true
  author:
  - name: "Alexandre Nicolella"
    affiliation: "Unversidade de São Paulo (USP)"
  - name: "José de Jesus Filho"
    affiliation: "PUC/SP"
  date: "06/10/2025"
  chapters:
      - index.qmd
      #- intro.qmd
      - autores.qmd
      - summary.qmd
      - desenho_jurimetria.qmd
      #- pesquisa.qmd
      - manipulacao.qmd
      - googledrive.qmd
      - dplyr.qmd
      - descritiva_v2.qmd
      - estatistica.qmd
      - lineares.qmd
      - outrosmodelos.qmd
      #- aprendizado.qmd
      #- interpretando.qmd
      #- dicionario.qmd
      #- references.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt


editor: visual

